Adding KubeCon presentations to WS marketing
inclusivenaming/org pull request #67
Opened 2021-05-27 19:24 UTC by xmulligan

2021-06-07 21:47 UTC, justaugustus requested changes
@xmulligan @celestehorgan -- Do we want to consider a Slideshare (or similar) account here and upload/link to those instead?

2021-06-07 22:40 UTC, xmulligan commented
I am personally in favor of less tools and accounts to keep it simple. Just add the decks to the Marketing WS drive and linking the decks. If someone has a strong opinion why Slideshare would be better, also open to change my mind

2021-06-07 23:24 UTC, justaugustus commented
> If someone has a strong opinion why Slideshare would be better, also open to change my mind

@xmulligan -- Not strong opinions per se with Slideshare in particular, but what I was thinking about is the fact that not all contributors will have access to Google Drive / Slides.

That said, we have that problem with anything that lands in Google Drive.

2021-06-08 16:52 UTC, celestehorgan approved these changes

2021-06-08 16:52 UTC, merged