Create tooling.md
inclusivenaming/org pull request #69
Opened 2021-06-07 17:19 UTC by celestehorgan

2021-06-07 23:16 UTC, justaugustus requested changes
@celestehorgan -- Tool eval is within the scope of WS Community, so maybe it want to send requests for eval to inclusivenaming@ and/or ws-community@ instead?

Ideally, we have an issue template to request demo time and point folks to that?
Thoughts here, @inclusivenaming/leads?

2021-06-07 23:18 UTC, justaugustus commented
@ddavisjones -- for input as well.

2021-06-08 16:43 UTC, celestehorgan commented
@justaugustus – maybe ws-community@ instead of leads?

2021-06-09 06:25 UTC, savage-alex commented
Looks good!!!!

2021-06-10 21:35 UTC, jasonbrooks commented
I think this looks good. 

+1 to having an issue template to request demo time.

2021-06-14 16:09 UTC, celestehorgan commented on ws-oss/tooling.md
> +the Inclusive Naming Initiative leads – please email leads@inclusivenaming.org to contact them.
```suggestion
the Inclusive Naming Community workstream – please email ws-community@inclusivenaming.org to contact them.
```

2021-06-14 16:09 UTC, merged